version: '3'
services:
  redmine:
    image: thaim/redmine
    volumes:
      - redmine_devel:/usr/src/redmine/
      - .:/usr/src/redmine/plugins/redmine_issue_view_count
    ports:
      - "80:3000"

volumes:
  redmine_devel:
